/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasCajero;

import Aplicacion.SistemaRestauranteFrames;
import Excepciones.IndiceArrayListException;
import Vistas.JFrmMenuCajero;
import javax.swing.JOptionPane;

/**
 *
 * @author Naomi
 */
public class JFrmCalcularPropina extends javax.swing.JFrame {

    /**
     * Creates new form JFrmCalcularPropina
     */
    public JFrmCalcularPropina() {
        initComponents();
        this.setLocationRelativeTo(null);
        imprimirCuentas();
    }

    private void imprimirCuentas() {

        for (int w = 0; w < SistemaRestauranteFrames.listapedidos.size(); w++) {
            this.textAreaVisualizarCuentas.append("CUENTA NO. " + w);
            this.textAreaVisualizarCuentas.append("\nNo. de Mesa: " + SistemaRestauranteFrames.listapedidos.get(w).getNumeroMesa());
            //CICLOS PARA CADA ALIMENTO
            for (int h = 0; h < SistemaRestauranteFrames.listapedidos.get(w).getPedido().getPlatillo().size(); h++) {
                this.textAreaVisualizarCuentas.append(SistemaRestauranteFrames.listapedidos.get(w).getPedido().getPlatillo().get(h).toString() + "\n");
            }
            for (int i = 0; i < SistemaRestauranteFrames.listapedidos.get(w).getPedido().getBebida().size(); i++) {
                this.textAreaVisualizarCuentas.append(SistemaRestauranteFrames.listapedidos.get(w).getPedido().getBebida().get(i).toString() + "\n");
            }
            for (int j = 0; j < SistemaRestauranteFrames.listapedidos.get(w).getPedido().getPostre().size(); j++) {
                this.textAreaVisualizarCuentas.append(SistemaRestauranteFrames.listapedidos.get(w).getPedido().getPostre().get(j).toString() + "\n");
            }
            this.textAreaVisualizarCuentas.append("\n");
            this.textAreaVisualizarCuentas.append("____________________________\n");
        }//CICLO FOR PARA IMPRIMIR LAS CUENTAS

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaVisualizarCuentas = new javax.swing.JTextArea();
        labelNoCuenta = new javax.swing.JLabel();
        labelSubtitulo = new javax.swing.JLabel();
        textNumeroCuenta = new javax.swing.JTextField();
        buttonCancelar = new javax.swing.JButton();
        buttonCalcularPropina = new javax.swing.JButton();
        labelSubtitulo2 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellidoPaterno = new javax.swing.JLabel();
        labelApellidoMaterno = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textApellidoPaterno = new javax.swing.JTextField();
        textApellidoMaterno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        labelTitulo.setText("Calculando Propina...");

        textAreaVisualizarCuentas.setColumns(20);
        textAreaVisualizarCuentas.setRows(5);
        jScrollPane1.setViewportView(textAreaVisualizarCuentas);

        labelNoCuenta.setText("No. Cuenta:");

        labelSubtitulo.setText("Seleccione el número de cuenta a la que le desea calcular la propina");

        buttonCancelar.setBackground(new java.awt.Color(204, 0, 0));
        buttonCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancelar.setText("Cancelar");
        buttonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelarMouseClicked(evt);
            }
        });

        buttonCalcularPropina.setBackground(new java.awt.Color(51, 153, 0));
        buttonCalcularPropina.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonCalcularPropina.setForeground(new java.awt.Color(255, 255, 255));
        buttonCalcularPropina.setText("Calcular");
        buttonCalcularPropina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCalcularPropinaMouseClicked(evt);
            }
        });

        labelSubtitulo2.setText("Ingrese los datos del empleado al que se le apuntará la propina");

        labelNombre.setText("Nombre:");

        labelApellidoPaterno.setText("Apellido Paterno:");

        labelApellidoMaterno.setText("Apellido Materno:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCalcularPropina))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(labelApellidoPaterno)
                            .addComponent(labelApellidoMaterno))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNombre)
                            .addComponent(textApellidoPaterno)
                            .addComponent(textApellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSubtitulo2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(labelSubtitulo)
                            .addGap(38, 38, 38))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(labelNoCuenta)
                            .addGap(29, 29, 29)
                            .addComponent(textNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(164, 164, 164)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelSubtitulo)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelNoCuenta))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelSubtitulo2)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelNombre))
                                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(labelApellidoPaterno))
                            .addComponent(textApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(labelApellidoMaterno))
                    .addComponent(textApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonCalcularPropina))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelarMouseClicked
        this.dispose();
        new JFrmMenuCajero().setVisible(true);
    }//GEN-LAST:event_buttonCancelarMouseClicked

    private void buttonCalcularPropinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCalcularPropinaMouseClicked

        try {
            int nocuenta = Integer.parseInt(this.textNumeroCuenta.getText());
            //Datos del empleado
            String name = this.textNombre.getText();
            String lastname1 = this.textApellidoPaterno.getText();
            String lastname2 = this.textApellidoMaterno.getText();

            if (nocuenta > SistemaRestauranteFrames.listapedidos.size() || nocuenta < 0) {
                throw new IndiceArrayListException("El número de cuenta ingresado no coincide"
                        + "\ncon el número de cuentas registradas");
            }

            //Se llama al método que calcula propinas para que calcule la propina de la cuenta seleccionada
            SistemaRestauranteFrames.listapedidos.get(nocuenta).calcularPropina(name, lastname1, lastname2);
            JOptionPane.showMessageDialog(null, "La propina se ha calculado correctamente");

        } catch (IndiceArrayListException except1) {
            JOptionPane.showMessageDialog(null, except1.getMessage());
        }

        this.textNumeroCuenta.setText("");
        this.textNombre.setText("");
        this.textApellidoPaterno.setText("");
        this.textApellidoMaterno.setText("");

    }//GEN-LAST:event_buttonCalcularPropinaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmCalcularPropina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmCalcularPropina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmCalcularPropina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmCalcularPropina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmCalcularPropina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcularPropina;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelApellidoMaterno;
    private javax.swing.JLabel labelApellidoPaterno;
    private javax.swing.JLabel labelNoCuenta;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelSubtitulo2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textApellidoMaterno;
    private javax.swing.JTextField textApellidoPaterno;
    private javax.swing.JTextArea textAreaVisualizarCuentas;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
