/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import VistasGerente.*;

/**
 *
 * @author Naomi
 */
public class JFrmMenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form JFrmMenuGerente
     */
    public JFrmMenuGerente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelOpciones = new javax.swing.JLabel();
        buttonAgregarEmpleado = new javax.swing.JButton();
        buttonEliminarEmpleado = new javax.swing.JButton();
        buttonEditarAlimento = new javax.swing.JButton();
        buttonEliminarAlimento = new javax.swing.JButton();
        buttonEstablecerSueldo = new javax.swing.JButton();
        buttonVerSueldo = new javax.swing.JButton();
        buttonVerPropinas = new javax.swing.JButton();
        buttonVerRegistro = new javax.swing.JButton();
        buttonVerMenu = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        labelTitulo.setText("BIENVENIDO GERENTE");

        labelOpciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelOpciones.setText("Seleccione una de las opciones del siguiente menú");

        buttonAgregarEmpleado.setText("1. Agregar Empleado");
        buttonAgregarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAgregarEmpleadoMouseClicked(evt);
            }
        });

        buttonEliminarEmpleado.setText("2. Eliminar Empleado");
        buttonEliminarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEliminarEmpleadoMouseClicked(evt);
            }
        });

        buttonEditarAlimento.setText("3. Añadir/Modificar Alimento");
        buttonEditarAlimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEditarAlimentoMouseClicked(evt);
            }
        });

        buttonEliminarAlimento.setText("4. Eliminar Alimento");
        buttonEliminarAlimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEliminarAlimentoMouseClicked(evt);
            }
        });

        buttonEstablecerSueldo.setText("5. Establecer Sueldo Empleado");
        buttonEstablecerSueldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEstablecerSueldoMouseClicked(evt);
            }
        });

        buttonVerSueldo.setText("6. Ver Sueldo Empleado");
        buttonVerSueldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVerSueldoMouseClicked(evt);
            }
        });

        buttonVerPropinas.setText("7. Ver Propinas");
        buttonVerPropinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVerPropinasMouseClicked(evt);
            }
        });

        buttonVerRegistro.setText("8. Ver Registro de Ventas");
        buttonVerRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVerRegistroMouseClicked(evt);
            }
        });

        buttonVerMenu.setText("9. Ver Menú");
        buttonVerMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVerMenuMouseClicked(evt);
            }
        });

        buttonSalir.setBackground(new java.awt.Color(204, 0, 0));
        buttonSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonSalir.setForeground(new java.awt.Color(255, 255, 255));
        buttonSalir.setText("Salir");
        buttonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(labelOpciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(labelTitulo)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonEstablecerSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonEliminarAlimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonEditarAlimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonEliminarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonVerSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonVerPropinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonVerRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonVerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOpciones)
                .addGap(18, 18, 18)
                .addComponent(buttonAgregarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEliminarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEditarAlimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEliminarAlimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEstablecerSueldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonVerSueldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonVerPropinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonVerRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonVerMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(buttonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgregarEmpleadoMouseClicked
        this.dispose();
        new JFrmCrearEmpleado().setVisible(true);
    }//GEN-LAST:event_buttonAgregarEmpleadoMouseClicked

    private void buttonEliminarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEliminarEmpleadoMouseClicked
        this.dispose();
        new JFrmEliminarEmpleado().setVisible(true);
    }//GEN-LAST:event_buttonEliminarEmpleadoMouseClicked

    private void buttonEditarAlimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditarAlimentoMouseClicked
        this.dispose();
        new JFrmEditarAlimentos().setVisible(true);
    }//GEN-LAST:event_buttonEditarAlimentoMouseClicked

    private void buttonEliminarAlimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEliminarAlimentoMouseClicked
        this.dispose();
        new JFrmEliminarAlimento().setVisible(true);
    }//GEN-LAST:event_buttonEliminarAlimentoMouseClicked

    private void buttonEstablecerSueldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEstablecerSueldoMouseClicked
        this.dispose();
        new JFrmSueldoEmpleado().setVisible(true);
    }//GEN-LAST:event_buttonEstablecerSueldoMouseClicked

    private void buttonVerMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVerMenuMouseClicked
        this.dispose();
        new JFrmVerMenu().setVisible(true);
    }//GEN-LAST:event_buttonVerMenuMouseClicked

    private void buttonVerSueldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVerSueldoMouseClicked
        this.dispose();
        new JFrmVerSueldoEmpleado().setVisible(true);
    }//GEN-LAST:event_buttonVerSueldoMouseClicked

    private void buttonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalirMouseClicked
        this.dispose();
        new JFrmLoginGerente().setVisible(true);
    }//GEN-LAST:event_buttonSalirMouseClicked

    private void buttonVerPropinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVerPropinasMouseClicked
        this.dispose();
        new JFrmVerPropinas().setVisible(true);
    }//GEN-LAST:event_buttonVerPropinasMouseClicked

    private void buttonVerRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVerRegistroMouseClicked
        this.dispose();
        new JFrmVerRegistro().setVisible(true);
    }//GEN-LAST:event_buttonVerRegistroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMenuGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregarEmpleado;
    private javax.swing.JButton buttonEditarAlimento;
    private javax.swing.JButton buttonEliminarAlimento;
    private javax.swing.JButton buttonEliminarEmpleado;
    private javax.swing.JButton buttonEstablecerSueldo;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JButton buttonVerMenu;
    private javax.swing.JButton buttonVerPropinas;
    private javax.swing.JButton buttonVerRegistro;
    private javax.swing.JButton buttonVerSueldo;
    private javax.swing.JLabel labelOpciones;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
