/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import VistasCajero.JFrmCalcularPropina;
import VistasCajero.JFrmDevolverCambio;
import VistasCajero.JFrmEditarCuenta;
import VistasCajero.JFrmImprimirCuenta;

/**
 *
 * @author Naomi
 */
public class JFrmMenuCajero extends javax.swing.JFrame {

    /**
     * Creates new form JFrmMenuCajero
     */
    public JFrmMenuCajero() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSalir = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelSubtitulo = new javax.swing.JLabel();
        buttonEditarCuenta = new javax.swing.JButton();
        buttonCalcularPropina = new javax.swing.JButton();
        buttonDevolverCambio = new javax.swing.JButton();
        buttonImprimirCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonSalir.setBackground(new java.awt.Color(204, 0, 0));
        buttonSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonSalir.setForeground(new java.awt.Color(255, 255, 255));
        buttonSalir.setText("Salir");
        buttonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSalirMouseClicked(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        labelTitulo.setText("BIENVENIDO CAJERO");

        labelSubtitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelSubtitulo.setText("Seleccione una de las opciones del siguiente menú");

        buttonEditarCuenta.setText("1. Editar Cuenta");
        buttonEditarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEditarCuentaMouseClicked(evt);
            }
        });

        buttonCalcularPropina.setText("2. Calcular Propina");
        buttonCalcularPropina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCalcularPropinaMouseClicked(evt);
            }
        });

        buttonDevolverCambio.setText("3. Devolver Cambio");
        buttonDevolverCambio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDevolverCambioMouseClicked(evt);
            }
        });

        buttonImprimirCuenta.setText("4. Imprimir Cuenta");
        buttonImprimirCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonImprimirCuentaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(labelSubtitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(labelTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonDevolverCambio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(buttonImprimirCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(buttonCalcularPropina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(buttonEditarCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSubtitulo)
                .addGap(18, 18, 18)
                .addComponent(buttonEditarCuenta)
                .addGap(18, 18, 18)
                .addComponent(buttonCalcularPropina)
                .addGap(18, 18, 18)
                .addComponent(buttonDevolverCambio)
                .addGap(18, 18, 18)
                .addComponent(buttonImprimirCuenta)
                .addGap(18, 18, 18)
                .addComponent(buttonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalirMouseClicked
        this.dispose();
        new JFrmLoginCajero().setVisible(true);
    }//GEN-LAST:event_buttonSalirMouseClicked

    private void buttonCalcularPropinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCalcularPropinaMouseClicked
        this.dispose();
        new JFrmCalcularPropina().setVisible(true);
    }//GEN-LAST:event_buttonCalcularPropinaMouseClicked

    private void buttonDevolverCambioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDevolverCambioMouseClicked
        this.dispose();
        new JFrmDevolverCambio().setVisible(true);
    }//GEN-LAST:event_buttonDevolverCambioMouseClicked

    private void buttonImprimirCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonImprimirCuentaMouseClicked
        this.dispose();
        new JFrmImprimirCuenta().setVisible(true);
    }//GEN-LAST:event_buttonImprimirCuentaMouseClicked

    private void buttonEditarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditarCuentaMouseClicked
        this.dispose();
        new JFrmEditarCuenta().setVisible(true);
    }//GEN-LAST:event_buttonEditarCuentaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMenuCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcularPropina;
    private javax.swing.JButton buttonDevolverCambio;
    private javax.swing.JButton buttonEditarCuenta;
    private javax.swing.JButton buttonImprimirCuenta;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
