/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Aplicacion.SistemaRestauranteFrames;
import Excepciones.DatosLoginException;
import javax.swing.JOptionPane;

/**
 *
 * @author Naomi
 */
public class JFrmLoginGerente extends javax.swing.JFrame {

    /**
     * Creates new form LogginGerente
     */
    public JFrmLoginGerente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        buttonCrearGerente = new javax.swing.JButton();
        buttonRegresar = new javax.swing.JButton();
        labelUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        textContrasena = new javax.swing.JTextField();
        buttonIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelTitulo.setText("LOGIN GERENTE");

        buttonCrearGerente.setBackground(new java.awt.Color(0, 51, 153));
        buttonCrearGerente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonCrearGerente.setForeground(new java.awt.Color(255, 255, 255));
        buttonCrearGerente.setText("Crear Gerente");
        buttonCrearGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearGerenteActionPerformed(evt);
            }
        });

        buttonRegresar.setBackground(new java.awt.Color(204, 0, 0));
        buttonRegresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegresar.setText("Salir");
        buttonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegresarActionPerformed(evt);
            }
        });

        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelUsuario.setText("Usuario:");

        labelContrasena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelContrasena.setText("Contraseña:");

        buttonIngresar.setBackground(new java.awt.Color(51, 153, 0));
        buttonIngresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        buttonIngresar.setText("Ingresar");
        buttonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonIngresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelContrasena)
                            .addComponent(labelUsuario))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(labelTitulo)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonCrearGerente)
                .addGap(44, 44, 44)
                .addComponent(buttonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonIngresar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTitulo)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCrearGerente)
                    .addComponent(buttonRegresar)
                    .addComponent(buttonIngresar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegresarActionPerformed
        this.dispose();
        new JFrmInicio().setVisible(true);
    }//GEN-LAST:event_buttonRegresarActionPerformed

    private void buttonCrearGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearGerenteActionPerformed
        this.dispose();
        new JFrmCrearGerente().setVisible(true);
    }//GEN-LAST:event_buttonCrearGerenteActionPerformed

    private void buttonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIngresarMouseClicked

        try {
            String user = this.textUsuario.getText();
            String password = this.textContrasena.getText();

            //Se llama al método para verificar si los datos ingresados de la cuenta son correctos
            if ((SistemaRestauranteFrames.verificarCuenta(user, password, SistemaRestauranteFrames.gerenteprincipal, SistemaRestauranteFrames.listaempleados, "M")) == true) {
                this.dispose();
                new JFrmMenuGerente().setVisible(true);//Si los datos coinciden, se despliega la ventana con el menú de opciones del gerente
            } else {//Si los datos ingresados no coinciden con la cuenta, entonces se arroja una excepción
                throw new DatosLoginException("El usuario o la contraseña son incorrectos");
            }

        } catch (DatosLoginException except1) {
            JOptionPane.showMessageDialog(null, except1.getMessage());
        } catch (java.lang.NullPointerException except2) {
            JOptionPane.showMessageDialog(null, "Aún no se ha creado el Gerente"
                    + "\nHaga 'clic' en 'crear gerente'");
        }
        this.textUsuario.setText("");
        this.textContrasena.setText("");
    }//GEN-LAST:event_buttonIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmLoginGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmLoginGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmLoginGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmLoginGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmLoginGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCrearGerente;
    private javax.swing.JButton buttonIngresar;
    private javax.swing.JButton buttonRegresar;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JTextField textContrasena;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
