/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasGerente;

import Vistas.JFrmMenuGerente;

/**
 *
 * @author Naomi
 */
public class JFrmEditarAlimentos extends javax.swing.JFrame {

    /**
     * Creates new form JFrmAnaModiAlimentos
     */
    public JFrmEditarAlimentos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelSubtitulo = new javax.swing.JLabel();
        labelSubtitulo2 = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        menuAnadirAlimento = new javax.swing.JMenu();
        menuModificarAlimento = new javax.swing.JMenu();
        menuModificarPlatillo = new javax.swing.JMenu();
        menuModificarBebida = new javax.swing.JMenu();
        menuModificarPostre = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alimentos.jpg"))); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelTitulo.setText("Menú para");

        labelSubtitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelSubtitulo.setText("modificar los ");

        labelSubtitulo2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelSubtitulo2.setText("Alimentos del Menú");

        buttonCancelar.setBackground(new java.awt.Color(204, 0, 0));
        buttonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancelar.setText("Volver al Menú");
        buttonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelarMouseClicked(evt);
            }
        });

        menuOpciones.setText("Ver Opciones");

        menuAnadirAlimento.setText("Añadir Alimento");
        menuAnadirAlimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAnadirAlimentoMouseClicked(evt);
            }
        });
        menuOpciones.add(menuAnadirAlimento);

        menuModificarAlimento.setText("Modificar Alimento");

        menuModificarPlatillo.setText("Platillo");
        menuModificarPlatillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuModificarPlatilloMouseClicked(evt);
            }
        });
        menuModificarAlimento.add(menuModificarPlatillo);

        menuModificarBebida.setText("Bebida");
        menuModificarBebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuModificarBebidaMouseClicked(evt);
            }
        });
        menuModificarAlimento.add(menuModificarBebida);

        menuModificarPostre.setText("Postre");
        menuModificarPostre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuModificarPostreMouseClicked(evt);
            }
        });
        menuModificarAlimento.add(menuModificarPostre);

        menuOpciones.add(menuModificarAlimento);

        jMenuBar1.add(menuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSubtitulo2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelSubtitulo)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelTitulo)
                                .addGap(61, 61, 61)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(buttonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(labelImagen)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImagen)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelSubtitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSubtitulo2)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCancelar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelarMouseClicked
        this.dispose();
        new JFrmMenuGerente().setVisible(true);
    }//GEN-LAST:event_buttonCancelarMouseClicked

    private void menuAnadirAlimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAnadirAlimentoMouseClicked
        this.dispose();
        new JFrmAnadirAlimento().setVisible(true);
    }//GEN-LAST:event_menuAnadirAlimentoMouseClicked

    private void menuModificarPlatilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuModificarPlatilloMouseClicked
        this.dispose();
        new JFrmModificarPlatillo().setVisible(true);
    }//GEN-LAST:event_menuModificarPlatilloMouseClicked

    private void menuModificarBebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuModificarBebidaMouseClicked
        this.dispose();
        new JFrmModificarBebida().setVisible(true);
    }//GEN-LAST:event_menuModificarBebidaMouseClicked

    private void menuModificarPostreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuModificarPostreMouseClicked
        this.dispose();
        new JFrmModificarPostre().setVisible(true);
    }//GEN-LAST:event_menuModificarPostreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmEditarAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmEditarAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmEditarAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmEditarAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmEditarAlimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelSubtitulo2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JMenu menuAnadirAlimento;
    private javax.swing.JMenu menuModificarAlimento;
    private javax.swing.JMenu menuModificarBebida;
    private javax.swing.JMenu menuModificarPlatillo;
    private javax.swing.JMenu menuModificarPostre;
    private javax.swing.JMenu menuOpciones;
    // End of variables declaration//GEN-END:variables
}
