/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasGerente;

import Aplicacion.SistemaRestauranteFrames;
import Excepciones.TipoAlimentoException;
import javax.swing.JOptionPane;

/**
 *
 * @author Naomi
 */
public class JFrmAnadirAlimento extends javax.swing.JFrame {

    /**
     * Creates new form JFrmAnadirAlimento
     */
    public JFrmAnadirAlimento() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNombreAlimento = new javax.swing.JLabel();
        labelPrecioAlimento = new javax.swing.JLabel();
        labelTipoAlimento = new javax.swing.JLabel();
        textNombreAlimento = new javax.swing.JTextField();
        textPrecioAlimento = new javax.swing.JTextField();
        textTipoAlimento = new javax.swing.JTextField();
        buttonAnadirAlimento = new javax.swing.JButton();
        buttonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelTitulo.setText("Añadiendo Alimento/Bebida...");

        labelNombreAlimento.setText("Nombre del Alimento:");

        labelPrecioAlimento.setText("Precio del Alimento:");

        labelTipoAlimento.setText("Tipo de Alimento:");

        buttonAnadirAlimento.setBackground(new java.awt.Color(51, 153, 0));
        buttonAnadirAlimento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonAnadirAlimento.setForeground(new java.awt.Color(255, 255, 255));
        buttonAnadirAlimento.setText("Añadir");
        buttonAnadirAlimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAnadirAlimentoMouseClicked(evt);
            }
        });

        buttonRegresar.setBackground(new java.awt.Color(204, 0, 0));
        buttonRegresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegresar.setText("Terminar");
        buttonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(buttonRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAnadirAlimento)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombreAlimento)
                            .addComponent(labelPrecioAlimento)
                            .addComponent(labelTipoAlimento))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPrecioAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombreAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTipoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelTitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNombreAlimento)
                    .addComponent(textNombreAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textPrecioAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecioAlimento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textTipoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipoAlimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAnadirAlimento)
                    .addComponent(buttonRegresar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegresarMouseClicked
        this.dispose();
        new JFrmEditarAlimentos().setVisible(true);
    }//GEN-LAST:event_buttonRegresarMouseClicked

    private void buttonAnadirAlimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAnadirAlimentoMouseClicked

        try {
            String namefood = this.textNombreAlimento.getText();
            double pricefood = Double.parseDouble(this.textPrecioAlimento.getText());
            String typefood = this.textTipoAlimento.getText();

            //Si el tipo de alimento no es como los que ofrece el restaurante, entonces se maneja una excepción
            if (typefood.equals("Platillo") || typefood.equals("Bebida") || typefood.equals("Postre")) {
                //Si el tipo de comida coincide con los tipos de alimentos que se ofrecen, entonces se añade el alimento al menú
                SistemaRestauranteFrames.gerenteprincipal.agregarAlimento(namefood, pricefood, typefood);
                JOptionPane.showMessageDialog(null, "El alimento se ha añadido al menú correctamente");

            } else {//Si el tipo de comida es diferente de los que se ofrece, entonces arroja una excepción
                throw new TipoAlimentoException("Sólo hay 3 tipos de alimentos: Platillo, Bebida o Postre"
                        + "\n(Ingrese la primera letra en mayúscula)");
            }

        } catch (TipoAlimentoException except1) {
            JOptionPane.showMessageDialog(null, except1.getMessage());
        }

        this.textNombreAlimento.setText("");
        this.textPrecioAlimento.setText("");
        this.textTipoAlimento.setText("");

    }//GEN-LAST:event_buttonAnadirAlimentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmAnadirAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmAnadirAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmAnadirAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmAnadirAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmAnadirAlimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnadirAlimento;
    private javax.swing.JButton buttonRegresar;
    private javax.swing.JLabel labelNombreAlimento;
    private javax.swing.JLabel labelPrecioAlimento;
    private javax.swing.JLabel labelTipoAlimento;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textNombreAlimento;
    private javax.swing.JTextField textPrecioAlimento;
    private javax.swing.JTextField textTipoAlimento;
    // End of variables declaration//GEN-END:variables
}
