/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasMesero;

/**
 *
 * @author Naomi
 */
public class JFrmMenuEditarCuenta extends javax.swing.JFrame {

    /**
     * Creates new form JFrmMenuEditarPedido
     */
    public JFrmMenuEditarCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagen = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();
        menubarOpcionesModificar = new javax.swing.JMenuBar();
        menuOpcionesEdicion = new javax.swing.JMenu();
        menuEditarMesa = new javax.swing.JMenu();
        menuEditarPedido = new javax.swing.JMenu();
        menuEditarMetPago = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/food.jpg"))); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        labelTitulo.setText("Menú de Edición de la Cuenta");

        buttonCancelar.setBackground(new java.awt.Color(204, 0, 0));
        buttonCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancelar.setText("Cancelar");
        buttonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelarMouseClicked(evt);
            }
        });

        menuOpcionesEdicion.setText("Opciones para Modificar");

        menuEditarMesa.setText("No.Mesa");
        menuEditarMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEditarMesaMouseClicked(evt);
            }
        });
        menuOpcionesEdicion.add(menuEditarMesa);

        menuEditarPedido.setText("Pedido");
        menuEditarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEditarPedidoMouseClicked(evt);
            }
        });
        menuOpcionesEdicion.add(menuEditarPedido);

        menuEditarMetPago.setText("Método de Pago");
        menuEditarMetPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEditarMetPagoMouseClicked(evt);
            }
        });
        menuOpcionesEdicion.add(menuEditarMetPago);

        menubarOpcionesModificar.add(menuOpcionesEdicion);

        setJMenuBar(menubarOpcionesModificar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelTitulo)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelImagen)
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonCancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(labelImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCancelar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelarMouseClicked
        this.dispose();
        new JFrmEditarCuenta().setVisible(true);
    }//GEN-LAST:event_buttonCancelarMouseClicked

    private void menuEditarMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditarMesaMouseClicked
        this.dispose();
        new JFrmEditarNoMesa().setVisible(true);
    }//GEN-LAST:event_menuEditarMesaMouseClicked

    private void menuEditarMetPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditarMetPagoMouseClicked
        this.dispose();
        new JFrmEditarMetodoPago().setVisible(true);
    }//GEN-LAST:event_menuEditarMetPagoMouseClicked

    private void menuEditarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditarPedidoMouseClicked
        this.dispose();
        new JFrmEditarPedido().setVisible(true);
    }//GEN-LAST:event_menuEditarPedidoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuEditarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuEditarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuEditarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuEditarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMenuEditarCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JMenu menuEditarMesa;
    private javax.swing.JMenu menuEditarMetPago;
    private javax.swing.JMenu menuEditarPedido;
    private javax.swing.JMenu menuOpcionesEdicion;
    private javax.swing.JMenuBar menubarOpcionesModificar;
    // End of variables declaration//GEN-END:variables
}
